// Local backup dataset of 52 scholarship schemes
export const LOCAL_SCHOLARSHIPS = [
  {
    "id": "central-001",
    "name": "Central Sector Scheme of Scholarships for College and University Students",
    "authority": "Ministry of Education, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 4.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "PG"],
    "min_percentage": 80.0,
    "amount_min": 12000,
    "amount_max": 20000,
    "deadline": "2026-10-31",
    "documents_required": ["Class 12 marksheet", "Income certificate", "Aadhaar card", "Bank passbook", "Enrollment certificate"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Scholarship for college and university students who are above 80th percentile of successful candidates in the relevant stream from the respective Board.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-sc-001",
    "name": "Post-Matric Scholarship for Scheduled Caste Students",
    "authority": "Ministry of Social Justice and Empowerment, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["SC"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Post-Matric", "Diploma", "UG", "PG"],
    "min_percentage": 0.0,
    "amount_min": 12000,
    "amount_max": 48000,
    "deadline": "2026-11-15",
    "documents_required": ["SC caste certificate", "Income certificate (< 2.5L)", "Marksheet", "Aadhaar card", "Bank passbook"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Financial assistance to SC students pursuing post-matric or post-secondary courses in recognized institutions.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-st-001",
    "name": "Post-Matric Scholarship for Scheduled Tribe Students",
    "authority": "Ministry of Tribal Affairs, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["ST"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Post-Matric", "Diploma", "UG", "PG"],
    "min_percentage": 0.0,
    "amount_min": 12000,
    "amount_max": 45000,
    "deadline": "2026-11-15",
    "documents_required": ["ST caste certificate", "Income certificate (< 2.5L)", "Marksheet", "Aadhaar card", "Bank passbook"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Financial assistance to ST students pursuing post-matric or post-secondary courses to complete their education.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-obc-001",
    "name": "Post-Matric Scholarship for OBC Students (NSP)",
    "authority": "Ministry of Social Justice and Empowerment, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["OBC"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Post-Matric", "Diploma", "UG", "PG"],
    "min_percentage": 50.0,
    "amount_min": 8000,
    "amount_max": 25000,
    "deadline": "2026-10-31",
    "documents_required": ["OBC caste certificate", "Income certificate (< 2.5L)", "Marksheet", "Aadhaar card", "Bank passbook"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Provides financial aid to OBC students from low-income families pursuing post-matriculation courses.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-minority-001",
    "name": "Post-Matric Scholarship Scheme for Minorities",
    "authority": "Ministry of Minority Affairs, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["Minority"],
    "income_max_lakh": 2.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Post-Matric", "Diploma", "UG", "PG"],
    "min_percentage": 50.0,
    "amount_min": 6000,
    "amount_max": 15000,
    "deadline": "2026-10-31",
    "documents_required": ["Self-declaration of minority community", "Income certificate", "Previous class marksheet", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Scholarships for students belonging to Muslims, Sikhs, Christians, Buddhists, Jain and Zoroastrians (Parsis) to pursue higher education.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-minority-002",
    "name": "Merit Cum Means Scholarship for Professional and Technical Courses CS",
    "authority": "Ministry of Minority Affairs, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["Minority"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "PG"],
    "min_percentage": 50.0,
    "amount_min": 25000,
    "amount_max": 30000,
    "deadline": "2026-10-31",
    "documents_required": ["Minority certificate", "Income certificate", "Verification from college", "Aadhaar card", "Fee receipt"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Scholarship targeting minority community students pursuing professional or technical undergraduate or postgraduate courses.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-pwd-001",
    "name": "Scholarships for Top Class Education for Students with Disabilities",
    "authority": "Department of Empowerment of Persons with Disabilities",
    "source_type": "Central Government",
    "category_eligibility": ["PWD"],
    "income_max_lakh": 6.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "PG", "Diploma"],
    "min_percentage": 50.0,
    "amount_min": 24000,
    "amount_max": 200000,
    "deadline": "2026-11-30",
    "documents_required": ["Disability certificate (40% or more)", "Income certificate", "Aadhaar card", "Fee receipt", "Marksheet"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Supports disabled students to pursue higher education in top-class recognized institutions with full tuition coverage.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-pwd-002",
    "name": "Post-Matric Scholarship for Students with Disabilities",
    "authority": "Department of Empowerment of Persons with Disabilities",
    "source_type": "Central Government",
    "category_eligibility": ["PWD"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Post-Matric", "Diploma", "UG", "PG"],
    "min_percentage": 0.0,
    "amount_min": 10000,
    "amount_max": 30000,
    "deadline": "2026-11-30",
    "documents_required": ["Disability certificate", "Income certificate", "Marksheet", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Provides financial aid to disabled students for post-matric studies.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-nmmss-001",
    "name": "National Means Cum Merit Scholarship Scheme (NMMSS)",
    "authority": "Department of School Education and Literacy, Govt of India",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 3.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Pre-Matric"],
    "min_percentage": 55.0,
    "amount_min": 12000,
    "amount_max": 12000,
    "deadline": "2026-09-30",
    "documents_required": ["Income certificate", "Class 8 marksheet", "Caste certificate (if applicable)", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Financial help to meritorious students of economically weaker sections to arrest their drop-out at class 8 and encourage them to continue education.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-inspire-001",
    "name": "INSPIRE Scholarship for Higher Education (SHE)",
    "authority": "Department of Science and Technology, Govt of India",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 999.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "PG"],
    "min_percentage": 90.0,
    "amount_min": 80000,
    "amount_max": 80000,
    "deadline": "2026-08-31",
    "documents_required": ["Class 12 marksheet (top 1% rank proof)", "Endorsement letter from college", "Aadhaar card"],
    "apply_url": "http://www.online-inspire.gov.in",
    "description": "Scholarship for top 1% students in board exams pursuing Natural and Basic Sciences at BSc, BS, MSc levels.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-aicte-pragati-001",
    "name": "AICTE Pragati Scholarship Scheme for Girl Students (Degree)",
    "authority": "AICTE, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 8.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG"],
    "min_percentage": 0.0,
    "amount_min": 50000,
    "amount_max": 50000,
    "deadline": "2026-10-31",
    "documents_required": ["Admission letter", "Tuition fee receipt", "Income certificate (< 8L)", "Self-attested marksheets", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Promotes technical education among girls. Provides ₹50,000 per annum for tuition and other study-related expenses.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-aicte-pragati-002",
    "name": "AICTE Pragati Scholarship Scheme for Girl Students (Diploma)",
    "authority": "AICTE, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 8.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Diploma"],
    "min_percentage": 0.0,
    "amount_min": 50000,
    "amount_max": 50000,
    "deadline": "2026-10-31",
    "documents_required": ["Admission letter", "Tuition fee receipt", "Income certificate (< 8L)", "Previous marksheet", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Supports girls pursuing polytechnic or engineering diplomas in AICTE-approved institutions.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-aicte-saksham-001",
    "name": "AICTE Saksham Scholarship Scheme for Specially Abled Students (Degree)",
    "authority": "AICTE, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["PWD"],
    "income_max_lakh": 8.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG"],
    "min_percentage": 0.0,
    "amount_min": 50000,
    "amount_max": 50000,
    "deadline": "2026-10-31",
    "documents_required": ["Disability certificate", "Admission proof", "Tuition fee receipt", "Income certificate", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Financial assistance to disabled students pursuing professional undergraduate degree programs.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-aicte-saksham-002",
    "name": "AICTE Saksham Scholarship Scheme for Specially Abled Students (Diploma)",
    "authority": "AICTE, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["PWD"],
    "income_max_lakh": 8.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Diploma"],
    "min_percentage": 0.0,
    "amount_min": 50000,
    "amount_max": 50000,
    "deadline": "2026-10-31",
    "documents_required": ["Disability certificate", "Admission proof", "Tuition fee receipt", "Income certificate", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Financial assistance to disabled students pursuing polytechnic diploma programs.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-pmss-001",
    "name": "Prime Minister's Scholarship Scheme (PMSS) for CAPFs & Assam Rifles",
    "authority": "Welfare and Rehabilitation Board, Ministry of Home Affairs",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 999.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG"],
    "min_percentage": 60.0,
    "amount_min": 30000,
    "amount_max": 36000,
    "deadline": "2026-10-15",
    "documents_required": ["Service certificate of parent", "Class 12 marksheet", "Bank passbook", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Promotes higher professional education for wards and widows of Central Armed Police Forces & Assam Rifles personnel.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-ugc-rank-001",
    "name": "UGC Post-Graduate Merit Scholarship for University Rank Holders",
    "authority": "University Grants Commission",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 999.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["PG"],
    "min_percentage": 60.0,
    "amount_min": 37200,
    "amount_max": 37200,
    "deadline": "2026-10-30",
    "documents_required": ["University rank certificate", "Graduation marksheet", "Admission slip in PG course", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "For first and second rank holders in undergraduate courses pursuing postgraduate education.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-ugc-single-girl-001",
    "name": "Indira Gandhi PG Scholarship for Single Girl Child",
    "authority": "University Grants Commission",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 999.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["PG"],
    "min_percentage": 0.0,
    "amount_min": 36200,
    "amount_max": 36200,
    "deadline": "2026-10-30",
    "documents_required": ["Single girl child affidavit", "PG Admission proof", "Marksheet", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Supports single girl child to pursue postgraduate education in colleges and universities.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-csss-001",
    "name": "Central Sector Scheme of Scholarship for College and University Students",
    "authority": "Department of Higher Education, Govt of India",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 4.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "PG"],
    "min_percentage": 80.0,
    "amount_min": 12000,
    "amount_max": 20000,
    "deadline": "2026-10-31",
    "documents_required": ["Income certificate", "Class 12 marksheet", "Admission proof", "Aadhaar card"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Financial assistance to students who secure above 80th percentile in Class 12 and are pursuing professional courses.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-pre-matric-sc-001",
    "name": "Pre-Matric Scholarship for SC Students (Class 9 and 10)",
    "authority": "Ministry of Social Justice and Empowerment, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["SC"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Pre-Matric"],
    "min_percentage": 0.0,
    "amount_min": 3500,
    "amount_max": 7000,
    "deadline": "2026-10-15",
    "documents_required": ["Caste certificate", "Income certificate (< 2.5L)", "Aadhaar card", "Previous marksheet"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Encourages children of SC parents to send their children to classes 9 & 10 to reduce drop-out rates.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-pre-matric-st-001",
    "name": "Pre-Matric Scholarship for ST Students (Class 9 and 10)",
    "authority": "Ministry of Tribal Affairs, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["ST"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Pre-Matric"],
    "min_percentage": 0.0,
    "amount_min": 3500,
    "amount_max": 7000,
    "deadline": "2026-10-15",
    "documents_required": ["Caste certificate", "Income certificate (< 2.5L)", "Aadhaar card", "Previous marksheet"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Aims to support tribal families to educate children in class 9 and 10.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-aicte-swanath-001",
    "name": "AICTE Swanath Scholarship Scheme (Degree)",
    "authority": "AICTE, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 8.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG"],
    "min_percentage": 0.0,
    "amount_min": 50000,
    "amount_max": 50000,
    "deadline": "2026-11-15",
    "documents_required": ["Orphan / Ward of Covid-19 casualty certificate", "Income certificate", "Aadhaar card", "Admission proof"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Supports orphans, wards of parents deceased in defense, and children of Covid-19 casualties to study.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "central-aicte-swanath-002",
    "name": "AICTE Swanath Scholarship Scheme (Diploma)",
    "authority": "AICTE, Government of India",
    "source_type": "Central Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 8.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["Diploma"],
    "min_percentage": 0.0,
    "amount_min": 50000,
    "amount_max": 50000,
    "deadline": "2026-11-15",
    "documents_required": ["Orphan / Ward of Covid-19 casualty certificate", "Income certificate", "Aadhaar card", "Admission proof"],
    "apply_url": "https://scholarships.gov.in",
    "description": "Supports orphans and other eligible children pursuing polytechnic diploma programs.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "gujarat-mysy-001",
    "name": "Mukhyamantri Yuva Swavalamban Yojana (MYSY)",
    "authority": "Government of Gujarat",
    "source_type": "State Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 6.0,
    "states_eligible": ["Gujarat"],
    "edu_levels_eligible": ["UG", "Diploma"],
    "min_percentage": 80.0,
    "amount_min": 25000,
    "amount_max": 200000,
    "deadline": "2026-09-30",
    "documents_required": ["Class 10/12 marksheet (80%+ percentile)", "Income certificate (< 6L)", "Domicile certificate", "Fee receipt", "Aadhaar card"],
    "apply_url": "https://mysy.guj.nic.in",
    "description": "Gujarat state scholarship providing up to ₹2 lakh for professional courses for students with excellent academic records.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "gujarat-digital-obc-001",
    "name": "Digital Gujarat BCK-81C Post-Matric Scholarship for OBC Students",
    "authority": "Social Justice & Empowerment Department, Gujarat",
    "source_type": "State Government",
    "category_eligibility": ["OBC"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Gujarat"],
    "edu_levels_eligible": ["UG", "PG", "Diploma"],
    "min_percentage": 50.0,
    "amount_min": 3000,
    "amount_max": 20000,
    "deadline": "2026-10-15",
    "documents_required": ["OBC caste certificate", "Income certificate (< 2.5L)", "Previous marksheet", "Domicile certificate", "Bank details"],
    "apply_url": "https://www.digitalgujarat.gov.in",
    "description": "Financial assistance to OBC students in Gujarat pursuing higher education after class 12.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "gujarat-digital-sc-001",
    "name": "Digital Gujarat BCK-6.1 Post-Matric Scholarship for SC Students",
    "authority": "Social Justice & Empowerment Department, Gujarat",
    "source_type": "State Government",
    "category_eligibility": ["SC"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Gujarat"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 5000,
    "amount_max": 50000,
    "deadline": "2026-10-15",
    "documents_required": ["SC caste certificate", "Income certificate", "Marksheet", "Aadhaar card", "Fee receipt"],
    "apply_url": "https://www.digitalgujarat.gov.in",
    "description": "Gujarat post-matric scholarship for scheduled caste students pursuing post-secondary courses.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "gujarat-digital-st-001",
    "name": "Digital Gujarat Umbrella Scheme for Education of ST Students",
    "authority": "Tribal Development Department, Gujarat",
    "source_type": "State Government",
    "category_eligibility": ["ST"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Gujarat"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 5000,
    "amount_max": 55000,
    "deadline": "2026-10-15",
    "documents_required": ["ST caste certificate", "Income certificate", "Marksheet", "Aadhaar card"],
    "apply_url": "https://www.digitalgujarat.gov.in",
    "description": "Post-matric scholarship scheme for ST students domiciled in Gujarat.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "maharashtra-mahadbt-ebc-001",
    "name": "Rajarshi Chhatrapati Shahu Maharaj Shikshan Shulkh Shishyavrutti Yojna",
    "authority": "Directorate of Higher Education, Government of Maharashtra",
    "source_type": "State Government",
    "category_eligibility": ["General", "EWS"],
    "income_max_lakh": 8.0,
    "states_eligible": ["Maharashtra"],
    "edu_levels_eligible": ["UG", "PG", "Diploma"],
    "min_percentage": 50.0,
    "amount_min": 10000,
    "amount_max": 100000,
    "deadline": "2026-08-31",
    "documents_required": ["Income certificate (< 8L)", "CAP Round admission letter", "Domicile certificate", "Previous class marksheet", "Declaration of two children"],
    "apply_url": "https://mahadbt.maharashtra.gov.in",
    "description": "Reimburses 50% of the tuition fee and exam fee for students admitted under general/EWS category in Maharashtra.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "maharashtra-mahadbt-obc-001",
    "name": "Post-Matric Scholarship to OBC Students - MahaDBT",
    "authority": "VJNT, OBC and SBC Welfare Department, Maharashtra",
    "source_type": "State Government",
    "category_eligibility": ["OBC"],
    "income_max_lakh": 1.5,
    "states_eligible": ["Maharashtra"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 4000,
    "amount_max": 20000,
    "deadline": "2026-08-31",
    "documents_required": ["OBC caste certificate", "Non-Creamy Layer certificate", "Income certificate (< 1.5L)", "Domicile certificate"],
    "apply_url": "https://mahadbt.maharashtra.gov.in",
    "description": "Provides tuition fee coverage and maintenance allowance to OBC students in Maharashtra.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "maharashtra-mahadbt-sc-001",
    "name": "Government of India Post-Matric Scholarship for SC Students - Maharashtra",
    "authority": "Social Justice & Special Assistance Department, Maharashtra",
    "source_type": "State Government",
    "category_eligibility": ["SC"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Maharashtra"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 10000,
    "amount_max": 60000,
    "deadline": "2026-08-31",
    "documents_required": ["SC caste certificate", "Income certificate", "Domicile certificate", "Previous class marksheet"],
    "apply_url": "https://mahadbt.maharashtra.gov.in",
    "description": "Full tuition and exam fee coverage for SC students residing and studying in Maharashtra.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "up-post-matric-gen-001",
    "name": "UP Scholarship Post-Matric (Other than Intermediate) for General Category",
    "authority": "Social Welfare Department, Uttar Pradesh",
    "source_type": "State Government",
    "category_eligibility": ["General"],
    "income_max_lakh": 2.0,
    "states_eligible": ["Uttar Pradesh"],
    "edu_levels_eligible": ["UG", "PG", "Diploma"],
    "min_percentage": 50.0,
    "amount_min": 5000,
    "amount_max": 30000,
    "deadline": "2026-11-30",
    "documents_required": ["Income certificate (< 2L)", "Caste certificate (General self-declaration)", "Domicile certificate", "Marksheet"],
    "apply_url": "https://scholarship.up.gov.in",
    "description": "Financial help for General category students studying UG/PG courses in Uttar Pradesh.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "up-post-matric-obc-001",
    "name": "UP Scholarship Post-Matric for OBC Category",
    "authority": "Backward Classes Welfare Department, Uttar Pradesh",
    "source_type": "State Government",
    "category_eligibility": ["OBC"],
    "income_max_lakh": 2.0,
    "states_eligible": ["Uttar Pradesh"],
    "edu_levels_eligible": ["UG", "PG", "Diploma"],
    "min_percentage": 50.0,
    "amount_min": 5000,
    "amount_max": 30000,
    "deadline": "2026-11-30",
    "documents_required": ["OBC Caste certificate", "Income certificate (< 2L)", "Domicile certificate", "Marksheet"],
    "apply_url": "https://scholarship.up.gov.in",
    "description": "Financial aid for OBC category college students in Uttar Pradesh.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "up-post-matric-scst-001",
    "name": "UP Scholarship Post-Matric for SC/ST Category",
    "authority": "Social Welfare Department, Uttar Pradesh",
    "source_type": "State Government",
    "category_eligibility": ["SC", "ST"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Uttar Pradesh"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 8000,
    "amount_max": 50000,
    "deadline": "2026-11-30",
    "documents_required": ["SC/ST Caste certificate", "Income certificate (< 2.5L)", "Domicile certificate", "Marksheet"],
    "apply_url": "https://scholarship.up.gov.in",
    "description": "Tuition fees reimbursement and allowance for SC/ST students in UP college institutions.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "wb-svmcm-001",
    "name": "Swami Vivekananda Merit Cum Means Scholarship (SVMCM)",
    "authority": "Government of West Bengal",
    "source_type": "State Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 2.5,
    "states_eligible": ["West Bengal"],
    "edu_levels_eligible": ["UG", "PG"],
    "min_percentage": 60.0,
    "amount_min": 12000,
    "amount_max": 96000,
    "deadline": "2026-09-15",
    "documents_required": ["Marksheet of Class 12 / UG (60%+ score)", "Income certificate (< 2.5L)", "Domicile proof (Voter ID/Aadhaar)", "Bank passbook"],
    "apply_url": "https://svmcm.wb.gov.in",
    "description": "Highly beneficial scholarship for West Bengal residents pursuing UG/PG courses with 60% and above.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "wb-oasis-sc-001",
    "name": "Oasis Post-Matric Scholarship for SC/ST Students - West Bengal",
    "authority": "Backward Classes Welfare Department, West Bengal",
    "source_type": "State Government",
    "category_eligibility": ["SC", "ST"],
    "income_max_lakh": 2.5,
    "states_eligible": ["West Bengal"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 50.0,
    "amount_min": 5000,
    "amount_max": 20000,
    "deadline": "2026-10-30",
    "documents_required": ["SC/ST caste certificate", "Income certificate", "Marksheet", "Domicile certificate"],
    "apply_url": "https://oasis.gov.in",
    "description": "Financial support for SC/ST students in West Bengal to pursue higher studies.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "karnataka-ssp-postmatric-001",
    "name": "SSP Post-Matric Scholarship for SC/ST Students",
    "authority": "Social Welfare Department, Government of Karnataka",
    "source_type": "State Government",
    "category_eligibility": ["SC", "ST"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Karnataka"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 10000,
    "amount_max": 50000,
    "deadline": "2026-08-15",
    "documents_required": ["Caste & Income certificate (Kutumba ID)", "College registration details", "Aadhaar card", "Marksheet"],
    "apply_url": "https://ssp.postmatric.karnataka.gov.in",
    "description": "State scholarship portal (SSP) scheme for SC/ST students pursuing post-matric courses in Karnataka.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "karnataka-ssp-obc-001",
    "name": "SSP Post-Matric Scholarship for OBC Students",
    "authority": "Backward Classes Welfare Department, Karnataka",
    "source_type": "State Government",
    "category_eligibility": ["OBC"],
    "income_max_lakh": 1.0,
    "states_eligible": ["Karnataka"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 50.0,
    "amount_min": 4000,
    "amount_max": 15000,
    "deadline": "2026-08-15",
    "documents_required": ["OBC caste & income certificate", "Marksheet", "Aadhaar card", "College fee receipt"],
    "apply_url": "https://ssp.postmatric.karnataka.gov.in",
    "description": "Provides fee concession and maintenance allowance to low-income OBC students in Karnataka.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "tamilnadu-postmatric-scst-001",
    "name": "Tamil Nadu Post-Matric Scholarship for SC/ST/SCC Students",
    "authority": "Adi Dravidar and Tribal Welfare Department, Tamil Nadu",
    "source_type": "State Government",
    "category_eligibility": ["SC", "ST"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Tamil Nadu"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 10000,
    "amount_max": 75000,
    "deadline": "2026-10-31",
    "documents_required": ["Community certificate", "Income certificate (< 2.5L)", "Attendance proof", "Previous class marksheet"],
    "apply_url": "https://www.escholarship.tn.gov.in",
    "description": "Free education scheme covering compulsory non-refundable fees and allowances for SC/ST students.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "tamilnadu-postmatric-obc-001",
    "name": "Tamil Nadu Post-Matric Scholarship for BC/MBC/DNC Students",
    "authority": "Backward Classes, Most Backward Classes Welfare Department, Tamil Nadu",
    "source_type": "State Government",
    "category_eligibility": ["OBC"],
    "income_max_lakh": 2.0,
    "states_eligible": ["Tamil Nadu"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 3000,
    "amount_max": 10000,
    "deadline": "2026-10-31",
    "documents_required": ["BC/MBC caste certificate", "Income certificate (< 2L)", "Aadhaar card", "Fee receipt"],
    "apply_url": "https://www.escholarship.tn.gov.in",
    "description": "Provides financial aid to students of backward/most backward classes pursuing post-secondary courses in government/aided colleges.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "bihar-postmatric-scst-001",
    "name": "Bihar Post-Matric Scholarship for SC/ST Students",
    "authority": "Backward and Extremely Backward Classes Welfare Department, Bihar",
    "source_type": "State Government",
    "category_eligibility": ["SC", "ST"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Bihar"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 5000,
    "amount_max": 15000,
    "deadline": "2026-09-30",
    "documents_required": ["Residential certificate of Bihar", "SC/ST caste certificate", "Income certificate", "Bonafide certificate from college"],
    "apply_url": "https://pmsonline.bih.nic.in",
    "description": "Bihar state portal scheme providing financial assistance to SC/ST college students.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "bihar-postmatric-obc-001",
    "name": "Bihar Post-Matric Scholarship for BC/EBC Students",
    "authority": "Backward and Extremely Backward Classes Welfare Department, Bihar",
    "source_type": "State Government",
    "category_eligibility": ["OBC"],
    "income_max_lakh": 3.0,
    "states_eligible": ["Bihar"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 0.0,
    "amount_min": 4000,
    "amount_max": 15000,
    "deadline": "2026-09-30",
    "documents_required": ["BC/EBC caste certificate", "Income certificate (< 3L)", "Domicile certificate", "Marksheet"],
    "apply_url": "https://pmsonline.bih.nic.in",
    "description": "Bihar state scholarship for OBC (BC/EBC) students pursuing undergraduate, postgraduate, or diploma programs.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "rajasthan-sje-postmatric-001",
    "name": "Rajasthan SJE Post-Matric Scholarship for SC/ST/OBC Students",
    "authority": "Social Justice and Empowerment Department, Rajasthan",
    "source_type": "State Government",
    "category_eligibility": ["SC", "ST", "OBC"],
    "income_max_lakh": 2.5,
    "states_eligible": ["Rajasthan"],
    "edu_levels_eligible": ["UG", "PG", "Diploma", "Post-Matric"],
    "min_percentage": 60.0,
    "amount_min": 5000,
    "amount_max": 20000,
    "deadline": "2026-10-31",
    "documents_required": ["Caste certificate", "Income certificate", "Jan Aadhaar card", "Marksheet of class 12"],
    "apply_url": "https://sjms.rajasthan.gov.in",
    "description": "Provides financial aid and tuition reimbursement for college-going students of backward classes in Rajasthan.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "delhi-ladli-001",
    "name": "Delhi Ladli Scheme - Higher Education Incentive",
    "authority": "Department of Women and Child Development, Delhi",
    "source_type": "State Government",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 1.0,
    "states_eligible": ["Delhi"],
    "edu_levels_eligible": ["Post-Matric", "UG", "Diploma"],
    "min_percentage": 0.0,
    "amount_min": 10000,
    "amount_max": 20000,
    "deadline": "2026-12-31",
    "documents_required": ["Delhi domicile certificate", "Income certificate (< 1L)", "Class 10/12 marksheets", "Aadhaar card"],
    "apply_url": "https://wcd.delhi.gov.in/wcd/delhi-ladli-scheme",
    "description": "Encourages girl students in Delhi to pursue higher studies by releasing long-term deposits upon completing grade milestones.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-tata-001",
    "name": "Tata Capital Pankh Scholarship Programme",
    "authority": "Tata Capital",
    "source_type": "CSR",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 4.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "Diploma"],
    "min_percentage": 60.0,
    "amount_min": 10000,
    "amount_max": 12000,
    "deadline": "2026-09-30",
    "documents_required": ["Class 12 marksheet (60%+ score)", "Annual Income certificate (< 4L)", "Admission fee receipt", "Aadhaar card", "Bank details"],
    "apply_url": "https://www.buddy4study.com/scholarship/tata-capital-pankh-scholarship",
    "description": "Financial help program by Tata Capital to support undergraduate and diploma students from lower-income backgrounds.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-hdfc-001",
    "name": "HDFC Bank Parivartan's ECS Scholarship (Undergraduate)",
    "authority": "HDFC Bank",
    "source_type": "CSR",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "Diploma"],
    "min_percentage": 55.0,
    "amount_min": 30000,
    "amount_max": 30000,
    "deadline": "2026-09-15",
    "documents_required": ["Previous class marksheet (55%+ score)", "Annual family income certificate (< 2.5L)", "Fee receipt", "Self-declaration of crisis (if applicable)"],
    "apply_url": "https://www.buddy4study.com/page/hdfc-bank-parivartans-ecs-scholarship",
    "description": "HDFC Parivartan scholarship designed for undergraduate students facing financial issues or family crises.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-hdfc-002",
    "name": "HDFC Bank Parivartan's ECS Scholarship (Postgraduate)",
    "authority": "HDFC Bank",
    "source_type": "CSR",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["PG"],
    "min_percentage": 55.0,
    "amount_min": 35000,
    "amount_max": 35000,
    "deadline": "2026-09-15",
    "documents_required": ["Graduation marksheet (55%+ score)", "Family income certificate (< 2.5L)", "Admission proof", "Aadhaar card"],
    "apply_url": "https://www.buddy4study.com/page/hdfc-bank-parivartans-ecs-scholarship",
    "description": "HDFC Parivartan scholarship designed for postgraduate students pursuing higher education.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-reliance-001",
    "name": "Reliance Foundation Undergraduate Scholarship",
    "authority": "Reliance Foundation",
    "source_type": "NGO",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 15.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG"],
    "min_percentage": 60.0,
    "amount_min": 100000,
    "amount_max": 200000,
    "deadline": "2026-10-15",
    "documents_required": ["Class 12 marksheet (60%+ score)", "Household income certificate (< 15L, preferred < 2.5L)", "Bonafide student certificate", "Aadhaar card"],
    "apply_url": "https://www.scholarships.reliancefoundation.org",
    "description": "A prestigious, merit-cum-means scholarship awarding up to ₹2 Lakhs over the course of UG program.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-reliance-002",
    "name": "Reliance Foundation Postgraduate Scholarship",
    "authority": "Reliance Foundation",
    "source_type": "NGO",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 999.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["PG"],
    "min_percentage": 75.0,
    "amount_min": 200000,
    "amount_max": 600000,
    "deadline": "2026-10-15",
    "documents_required": ["GATE/GPAT/JAM score or UG marksheet (75%+ score)", "CV / Resume", "Letter of recommendation", "Aadhaar card"],
    "apply_url": "https://www.scholarships.reliancefoundation.org",
    "description": "Recognizes and grooms high-potential PG students in science, technology, engineering, and mathematics fields.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-lic-001",
    "name": "LIC Golden Jubilee Scholarship Scheme",
    "authority": "LIC Golden Jubilee Foundation",
    "source_type": "NGO",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "Diploma"],
    "min_percentage": 60.0,
    "amount_min": 10000,
    "amount_max": 20000,
    "deadline": "2026-12-15",
    "documents_required": ["Class 12 marksheet (60%+)", "Income certificate (< 2.5L)", "Admission letter", "Bank account passbook", "Aadhaar card"],
    "apply_url": "https://www.licindia.in/Bottom-Links/Golden-Jubilee-Foundation/Scholarship",
    "description": "Aims to provide scholarships to meritorious students of economically weaker families for professional degree/diploma courses.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-kotak-kanya-001",
    "name": "Kotak Kanya Scholarship",
    "authority": "Kotak Education Foundation",
    "source_type": "CSR",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 6.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG"],
    "min_percentage": 75.0,
    "amount_min": 150000,
    "amount_max": 150000,
    "deadline": "2026-10-31",
    "documents_required": ["Class 12 marksheet (75%+ score)", "Family income certificate (< 6L)", "Admission fee payment proof", "Gender validation (Female only)"],
    "apply_url": "https://kotakeducation.org/kotak-kanya-scholarship",
    "description": "Financial and mentoring aid to girl students seeking higher professional courses in engineering, medicine, law, etc.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-colgate-001",
    "name": "Keep India Smiling Foundational Scholarship for Education (UG)",
    "authority": "Colgate-Palmolive (India) Ltd.",
    "source_type": "CSR",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 5.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "Diploma"],
    "min_percentage": 60.0,
    "amount_min": 30000,
    "amount_max": 30000,
    "deadline": "2026-12-31",
    "documents_required": ["Class 12 marksheet (60%+)", "Income proof (< 5L)", "Admission letter", "Disability certificate (if applicable)"],
    "apply_url": "https://www.buddy4study.com/colgate-keep-india-smiling-scholarship",
    "description": "Scholarship program targeting needy students to pursue undergraduate college courses.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-sitaram-001",
    "name": "Sitaram Jindal Foundation Scholarship",
    "authority": "Sitaram Jindal Foundation",
    "source_type": "NGO",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 2.5,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG", "PG", "Diploma"],
    "min_percentage": 60.0,
    "amount_min": 6000,
    "amount_max": 30000,
    "deadline": "2026-12-31",
    "documents_required": ["Previous class marksheet", "Family income certificate (< 2.5L)", "Aadhaar card", "Fee receipt"],
    "apply_url": "https://www.sitaramjindalfoundation.org/scholarships.php",
    "description": "Financial support for undergraduate, postgraduate, and ITI/Diploma students from marginalized backgrounds.",
    "is_active": true,
    "last_verified": "2026-06-20"
  },
  {
    "id": "ngo-loreal-001",
    "name": "L'Oreal India For Young Women In Science Scholarship",
    "authority": "L'Oreal India",
    "source_type": "CSR",
    "category_eligibility": ["ALL"],
    "income_max_lakh": 6.0,
    "states_eligible": ["ALL"],
    "edu_levels_eligible": ["UG"],
    "min_percentage": 85.0,
    "amount_min": 250000,
    "amount_max": 250000,
    "deadline": "2026-10-15",
    "documents_required": ["Class 12 marksheet (85%+ in PCM/PCB)", "Income certificate (< 6L)", "Aadhaar card", "College admission letter", "Gender check (Female only)"],
    "apply_url": "https://www.foryoungwomeninscience.co.in",
    "description": "Encourages young girls who have passed Class 12 to pursue careers in scientific fields.",
    "is_active": true,
    "last_verified": "2026-06-20"
  }
]

// Serverless client-side pre-filtering and matching engine
export const runLocalMatching = (formData) => {
  const score = parseFloat(formData.score);
  const scorePercentage = formData.score_type === 'cgpa' ? score * 9.5 : score;
  const incomeBracketLimit = {
    "<1L": 1.0,
    "1-2.5L": 2.5,
    "2.5-4.5L": 4.5,
    "4.5-6L": 6.0,
    "6-8L": 8.0,
    ">8L": 999.0
  };
  const studentIncomeLakh = incomeBracketLimit[formData.income_bracket] || 999.0;

  // 1. Pre-filter logic matching backend SQLite implementation
  const candidates = LOCAL_SCHOLARSHIPS.filter(s => {
    if (!s.is_active) return false;
    if (s.income_max_lakh < studentIncomeLakh) return false;
    if (s.min_percentage > scorePercentage) return false;

    // List containment check for Category
    const categoryMatch = s.category_eligibility.includes("ALL") || s.category_eligibility.includes(formData.category);
    
    // List containment check for Domicile State
    const stateMatch = s.states_eligible.includes("ALL") || s.states_eligible.includes(formData.state);

    // List containment check for Education Level
    const eduMatch = s.edu_levels_eligible.includes(formData.edu_level);

    return categoryMatch && stateMatch && eduMatch;
  });

  if (candidates.length === 0) {
    return {
      status: "no_results",
      count: 0,
      student_profile: {
        category: formData.category,
        income_bracket: formData.income_bracket,
        state: formData.state,
        edu_level: formData.edu_level,
        score_percentage: Math.round(scorePercentage * 10) / 10
      },
      scholarships: []
    };
  }

  // 2. Deterministic match ranking by amount_max descending
  const sorted = [...candidates].sort((a, b) => b.amount_max - a.amount_max);

  // 3. Format into output schema
  const formattedScholarships = sorted.map((c, idx) => {
    const formatDeadline = (dl) => {
      if (!dl) return "No fixed deadline / Rolling";
      try {
        const months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
        const parts = dl.split("-");
        const dt = new Date(parts[0], parts[1] - 1, parts[2]);
        return `${String(dt.getDate()).padStart(2, '0')}-${months[dt.getMonth()]}-${dt.getFullYear()}`;
      } catch (e) {
        return dl;
      }
    };

    const isDeadlineUrgent = (dl) => {
      if (!dl) return false;
      try {
        const parts = dl.split("-");
        const dt = new Date(parts[0], parts[1] - 1, parts[2]);
        const diff = dt - new Date();
        const days = diff / (1000 * 60 * 60 * 24);
        return days >= 0 && days <= 30;
      } catch (e) {
        return false;
      }
    };

    const reason = `You meet all criteria for ${c.name} (Income limit: ₹${c.income_max_lakh}L, Minimum score: ${c.min_percentage}%).`;

    return {
      id: c.id,
      name: c.name,
      authority: c.authority,
      source_type: c.source_type,
      amount_min: c.amount_min,
      amount_max: c.amount_max,
      amount_display: c.amount_min ? `₹${c.amount_min.toLocaleString('en-IN')} – ₹${c.amount_max.toLocaleString('en-IN')} per year` : `₹${c.amount_max.toLocaleString('en-IN')} per year`,
      deadline: c.deadline,
      deadline_display: formatDeadline(c.deadline),
      deadline_urgent: isDeadlineUrgent(c.deadline),
      documents_required: c.documents_required,
      apply_url: c.apply_url,
      eligibility_reason: reason,
      rank: idx + 1
    };
  });

  return {
    status: "success",
    count: formattedScholarships.length,
    student_profile: {
      category: formData.category,
      income_bracket: formData.income_bracket,
      state: formData.state,
      edu_level: formData.edu_level,
      score_percentage: Math.round(scorePercentage * 10) / 10
    },
    scholarships: formattedScholarships
  };
};
